/**
 * The starter trait pack. bingo/req.md §19.
 *
 * 104 traits, generated from req.md §19 — do not hand-edit; regenerate if the
 * requirements change. The master curates these down to exactly 81 (req §11.3).
 */
export type TraitCategory = 'faith' | 'church' | 'background' | 'taste' | 'fun';

export interface StarterTrait {
  readonly text: string;
  readonly category: TraitCategory;
}

export const TRAIT_CATEGORY_LABELS: Record<TraitCategory, string> = {
  faith: '신앙생활',
  church: '교회활동',
  background: '배경',
  taste: '개인취향',
  fun: '재미',
};

export const STARTER_TRAITS: readonly StarterTrait[] = [
  // 신앙생활
  { text: '새벽기도 참석해본 사람', category: 'faith' },
  { text: '성경 통독 완주해본 사람', category: 'faith' },
  { text: '암송 구절 10개 이상', category: 'faith' },
  { text: '세례받은 지 1년 미만', category: 'faith' },
  { text: '세례받은 지 10년 이상', category: 'faith' },
  { text: '큐티를 매일 하는 사람', category: 'faith' },
  { text: '성경책을 3권 이상 가진 사람', category: 'faith' },
  { text: '기도수첩이 있는 사람', category: 'faith' },
  { text: '금요철야 참석해본 사람', category: 'faith' },
  { text: '단기선교 다녀온 사람', category: 'faith' },
  { text: '수련회에서 울어본 사람', category: 'faith' },
  { text: '전도해본 경험이 있는 사람', category: 'faith' },
  { text: '성경 66권 순서를 외우는 사람', category: 'faith' },
  { text: '주일예배 1부에 오는 사람', category: 'faith' },
  { text: '교회에서 신앙 상담 받아본 사람', category: 'faith' },
  { text: '부흥회 참석해본 사람', category: 'faith' },
  { text: '성경필사 해본 사람', category: 'faith' },
  { text: '매일 성경 앱을 쓰는 사람', category: 'faith' },
  // 교회활동
  { text: '새가족 (3개월 미만)', category: 'church' },
  { text: '교회 10년 이상 다닌 사람', category: 'church' },
  { text: '찬양팀 경험이 있는 사람', category: 'church' },
  { text: '주일학교 교사 경험', category: 'church' },
  { text: '성가대 경험', category: 'church' },
  { text: '음향/미디어팀 경험', category: 'church' },
  { text: '주차봉사 해본 사람', category: 'church' },
  { text: '식당봉사 해본 사람', category: 'church' },
  { text: '셀 리더 경험', category: 'church' },
  { text: '청년부 출신', category: 'church' },
  { text: '중고등부 출신', category: 'church' },
  { text: '유아세례 받은 사람', category: 'church' },
  { text: '교회에서 결혼식 올린 사람', category: 'church' },
  { text: '부모님도 같은 교회', category: 'church' },
  { text: '교회 수련회 총무 해본 사람', category: 'church' },
  { text: '교회 차량 운전해본 사람', category: 'church' },
  { text: '헌금위원 해본 사람', category: 'church' },
  { text: '교회 행사 사회 봐본 사람', category: 'church' },
  // 배경
  { text: '형제자매가 3명 이상', category: 'background' },
  { text: '외동', category: 'background' },
  { text: '쌍둥이', category: 'background' },
  { text: '서울 출신', category: 'background' },
  { text: '부산 출신', category: 'background' },
  { text: '제주도에서 살아본 사람', category: 'background' },
  { text: '해외에서 1년 이상 살아본 사람', category: 'background' },
  { text: '유학 경험이 있는 사람', category: 'background' },
  { text: '군대 다녀온 사람', category: 'background' },
  { text: '이사를 5번 이상 해본 사람', category: 'background' },
  { text: '지금 자취 중인 사람', category: 'background' },
  { text: '결혼한 사람', category: 'background' },
  { text: '자녀가 있는 사람', category: 'background' },
  { text: '손주가 있는 사람', category: 'background' },
  { text: '반려동물을 키우는 사람', category: 'background' },
  { text: '고양이를 키우는 사람', category: 'background' },
  { text: '강아지를 키우는 사람', category: 'background' },
  { text: '대가족과 함께 사는 사람', category: 'background' },
  { text: '30분 이상 걸려서 교회 오는 사람', category: 'background' },
  { text: '걸어서 교회 오는 사람', category: 'background' },
  // 개인취향
  { text: '커피보다 차를 좋아하는 사람', category: 'taste' },
  { text: '아메리카노만 마시는 사람', category: 'taste' },
  { text: '민트초코를 좋아하는 사람', category: 'taste' },
  { text: '매운 음식을 잘 먹는 사람', category: 'taste' },
  { text: '회를 못 먹는 사람', category: 'taste' },
  { text: '아침형 인간', category: 'taste' },
  { text: '저녁형 인간', category: 'taste' },
  { text: '등산을 좋아하는 사람', category: 'taste' },
  { text: '러닝을 하는 사람', category: 'taste' },
  { text: '헬스장에 다니는 사람', category: 'taste' },
  { text: '축구를 좋아하는 사람', category: 'taste' },
  { text: '야구팀 팬인 사람', category: 'taste' },
  { text: '악기를 다룰 수 있는 사람', category: 'taste' },
  { text: '피아노를 칠 줄 아는 사람', category: 'taste' },
  { text: '기타를 칠 줄 아는 사람', category: 'taste' },
  { text: '노래방 애창곡이 있는 사람', category: 'taste' },
  { text: '그림을 잘 그리는 사람', category: 'taste' },
  { text: '사진 찍는 걸 좋아하는 사람', category: 'taste' },
  { text: '책을 한 달에 1권 이상 읽는 사람', category: 'taste' },
  { text: '드라마를 정주행하는 사람', category: 'taste' },
  { text: '요리를 즐겨 하는 사람', category: 'taste' },
  { text: '베이킹을 해본 사람', category: 'taste' },
  { text: '식물을 키우는 사람', category: 'taste' },
  { text: '캠핑을 좋아하는 사람', category: 'taste' },
  // 재미
  { text: '이름이 3글자가 아닌 사람', category: 'fun' },
  { text: '성이 김/이/박이 아닌 사람', category: 'fun' },
  { text: '생일이 이번 달인 사람', category: 'fun' },
  { text: '나와 같은 띠인 사람', category: 'fun' },
  { text: '왼손잡이', category: 'fun' },
  { text: '안경을 쓴 사람', category: 'fun' },
  { text: '렌즈를 낀 사람', category: 'fun' },
  { text: '오늘 처음 인사한 사람', category: 'fun' },
  { text: '지금 입은 옷이 파란색인 사람', category: 'fun' },
  { text: '운동화를 신은 사람', category: 'fun' },
  { text: 'MBTI가 I로 시작하는 사람', category: 'fun' },
  { text: 'MBTI가 E로 시작하는 사람', category: 'fun' },
  { text: '휴대폰 배경화면이 사람 사진인 사람', category: 'fun' },
  { text: '아이폰 쓰는 사람', category: 'fun' },
  { text: '갤럭시 쓰는 사람', category: 'fun' },
  { text: '운전면허가 없는 사람', category: 'fun' },
  { text: '자전거를 탈 줄 모르는 사람', category: 'fun' },
  { text: '수영을 할 줄 아는 사람', category: 'fun' },
  { text: '외국어를 2개 이상 하는 사람', category: 'fun' },
  { text: '사투리를 쓰는 사람', category: 'fun' },
  { text: '별명이 있는 사람', category: 'fun' },
  { text: '오늘 아침을 먹고 온 사람', category: 'fun' },
  { text: '지각한 사람', category: 'fun' },
  { text: '어제 6시간 이하로 잔 사람', category: 'fun' },
] as const;

export const STARTER_TRAIT_COUNT = STARTER_TRAITS.length; // 104

/**
 * This event's real 5×5 card (온누리 Win2 순장 OT). Exactly CELLS (25) traits, in order —
 * the console loads these as the default trait list. `STARTER_TRAITS` stays as an extra pool.
 */
export const DEFAULT_BINGO_TRAITS: readonly string[] = [
  '선교 갔다 온 사람',
  'ISFP인 사람',
  '안경 쓴 사람',
  '지난주 새벽기도 참석한 사람',
  '성경 통독 완주해 본 사람',
  '어제 QT 한 사람',
  'MBTI가 J인 사람',
  'MBTI가 I인 사람',
  'MBTI가 T인 사람',
  '나랑 신발 사이즈 같은 사람',
  'Galaxy 쓰는 사람',
  '세례 받은 지 10년 이상 된 사람',
  '수련회에서 울어본 사람 😂',
  'FREE — 옆 사람과 하이파이브 ✋',
  '크로스 러닝 나가본 사람',
  '최근 2주 안에 영화관에서 영화 본 사람',
  '나랑 양말 색깔 같은 사람',
  '귀 뚫은 사람',
  '나랑 성이 같은 사람',
  '오늘 처음 대화해보는 사람',
  '다른 공동체에서 섬기는 사람',
  '나랑 생일 달이 같은 사람',
  '나랑 동갑인 사람',
  '배터리 30% 이하인 사람 🔋',
  '오늘 커피 마신 사람 ☕',
] as const;
